### PR TITLE
[Client] add initial client code

### PR DESCRIPTION
**Pull request by michaelfeil**

### CODE REVIEW

**Comment by michaelfeil** [comment]
Wow, greptile just threw out a ton of cool comments! Well done @dakshgup

**Comment by molntamas** [comment]
Hi @michaelfeil,

Do you know when this client gonna be stable and usable?

I was looking for a plain HTTP client for infinity API for the embedding endpoint.
I wouldn't like to use langchain or other libraries.
The client in this PR seems like what I'm looking for.

Thanks a lot! :)

**Comment by michaelfeil** [comment]
The client is working -> But want to make sure its also performant first. It's a tiny wrapper around ~requests / httpx, the openapi.json / http endpoints are pretty stable

**Comment by molntamas** [comment]
Thanks, I have added the current version of the client, to use the API for evaluation of some models.
So far it works fine.

**Pull request merged**
