### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by LetsssGo55**
Fixed some important grammatical error ,change the url  Before
[https:///michaelfeil.github.io/infinity]
After
[https://michaelfeil.github.io/infinity/latest/]

### CODE REVIEW

**Comment by michaelfeil** [comment]
Bot pr?

**Comment by LetsssGo55** [comment]
This is not bot Pull request.

**Comment by LetsssGo55** [comment]
Can u merge it i think i have made valuable contribution.

**Comment by michaelfeil** [comment]
@LetsssGo55 You created github profile 4 weeks ago, and only add readme.
The contribution is incorrect, the link wrong. 

I can't think of any other use case than gaming the GitHub permission system to be marked as "contributor" to "steal" e.g. secrets from the project settings.

**Pull request closed without merging**
